pator/blueprints/tutee.py
from flask import (
    Blueprint, flash, g, redirect, render_template, request, url_for
)
from jinja2 import TemplateNotFound
from werkzeug.exceptions import abort

from pator.blueprints.auth import login_required
from pator.db import get_db

bp = Blueprint('course', __name__, url_prefix='/course')
# bp_create = Blueprint('create', __name__, url_prefix='/create')

# bp.register_blueprint(bp_create)

def get_courses(query=None, type='category'):
    db = get_db()
    cursor = db.cursor(dictionary=True)

    #  if query is None, return every course
    if query is None:
        cursor.execute(
            '''
            SELECT c.course_name, c.course_prodi, cp.course_rating, cp.hourly_fee, cp.id AS course_tutor_id, u.name
            FROM course c
            INNER JOIN course_tutor cp ON (c.id = cp.course_id)
            INNER JOIN tutor t ON (cp.tutor_id = t.id)
            INNER JOIN user u ON (t.user_id = u.id)
            '''
        )
        
        datas = cursor.fetchall()

        return datas

    # if query is not none, execute query statement based on type
    if type == "category":
        category_name = f"%{query}%"

        cursor.execute(
            '''
            SELECT c.course_name, c.course_prodi, cp.course_rating, cp.hourly_fee, cp.id AS course_tutor_id, u.name
            FROM course c
            INNER JOIN course_tutor cp ON (c.id = cp.course_id)
            INNER JOIN tutor t ON (cp.tutor_id = t.id)
            INNER JOIN user u ON (t.user_id = u.id)
            WHERE c.course_prodi LIKE %s
            ''',
            (category_name,)
        )
    elif type == "search":
        search_query = f"%{query}%"

        cursor.execute(
            '''
            SELECT c.course_name, c.course_prodi, cp.course_rating, cp.hourly_fee, cp.id AS course_tutor_id, u.name
            FROM course c
            INNER JOIN course_tutor cp ON (c.id = cp.course_id)
            INNER JOIN tutor t ON (cp.tutor_id = t.id)
            INNER JOIN user u ON (t.user_id = u.id)
            WHERE c.course_name LIKE %s 
            OR u.name LIKE %s
            ''',
            (search_query, search_query,)
        )

    datas = cursor.fetchall()

    return datas


@bp.route('/category', defaults={'name': None})
@bp.route('/category/<name>', methods=(['GET']))
def category(name):
    datas = get_courses(name, "category")

    if name is not None:
        return render_template('tutee/list.html', datas=datas, category=name.title())
    else:
        return render_template('tutee/list.html', datas=datas)

@bp.route('/search', methods=(['GET']))
def search():
    query = request.args.get('query')
    
    datas = get_courses(query, "search")

    if query is not None:
        return render_template('tutee/list.html', datas=datas, category=query.title())
    else:
        return render_template('tutee/list.html', datas=datas)


@bp.route('/detail', defaults={'id': None})
@bp.route('/detail/<int:id>', methods=(['GET']))
def detail(id):
    db = get_db()
    cursor = db.cursor(dictionary=True)


    # TODO: Add more inner join to tables course_tutor_keyword and tutor_session_review
    cursor.execute(
        '''
        SELECT c.course_name, c.course_prodi, cp.course_rating, cp.hourly_fee, cp.id AS course_tutor_id, u.name,
        cp.course_description, t.self_description
        FROM course_tutor cp
        INNER JOIN course c ON (cp.course_id = c.id)
        INNER JOIN tutor t ON (cp.tutor_id = t.id)
        INNER JOIN user u ON (t.user_id = u.id)
        WHERE cp.id = %s
        ''',
        (id,)
    )

    data = cursor.fetchone()

    if data is not None:
        return render_template('tutee/detail.html', data=data)
    
    abort(404)

@bp.route('/payment', defaults={'id': None})
@bp.route('/payment/<int:id>', methods=('GET', 'POST'))
@login_required
def payment(id):
    if id is None:
        return redirect(request.referrer)

    if request.method == 'GET':
        hours = request.args.get('hours')

        db = get_db()
        cursor = db.cursor(dictionary=True)

        cursor.execute(
            '''
            SELECT c.course_name, c.course_prodi, cp.course_rating, cp.hourly_fee, cp.id AS course_tutor_id, u.name, u.id
            FROM course_tutor cp
            INNER JOIN course c ON (cp.course_id = c.id)
            INNER JOIN tutor t ON (cp.tutor_id = t.id)
            INNER JOIN user u ON (t.user_id = u.id)
            WHERE cp.id = %s
            ''',
            (id,)
        )

        data = cursor.fetchone()

        data['total_fee'] = data['hourly_fee'] * int(hours)

        if data is not None:
            return render_template('tutee/payment.html', data=data)
    
        abort(400)

    elif request.method == 'POST':
        course_tutor_id = request.form.get('course_tutor_id', None)
        tutor_id = request.form.get('tutor_id', None)
        user_id = g.user['id']

        db = get_db()
        cursor = db.cursor(dictionary=True)
        error = None

        if None in (course_tutor_id, tutor_id):
            error = "Please check you request data."

        if error is None:
            course_tutor_id = int(course_tutor_id)
            tutor_id = int(tutor_id)

            cursor.execute('SELECT * FROM tutee WHERE user_id = %s', (user_id,)) 

            tutee = cursor.fetchone()

            if tutee is None:
                cursor.execute('INSERT INTO tutee (user_id) VALUES (%s)', (user_id,))
                tutee_id = cursor.lastrowid
            else:
                tutee_id = tutee['id']

            cursor.execute(
                '''
                INSERT INTO tutor_session (course_tutor_id, tutor_id, tutee_id)
                VALUES (%s, %s, %s)
                ''',
                (course_tutor_id, tutor_id, tutee_id,)
            )

            return redirect(url_for('course.success'))

        abort(400)

@bp.route('/payment-success', methods=(['GET']))
def success():
    try:
        return render_template('tutee/success.html')
    except TemplateNotFound:
        abort(404)

pator/templates/tutee/detail.html
{% extends 'base.html' %}

{% block title %}Course Detail{% endblock %}

{% block content %}
<!-- deskripsi -->
<section class="checkout d-flex flex-column justify-content-center align-items-center">
    <div class="container">
        <div class="row">
            <div class="col-md-8 judul">
                <h1>{{ data["course_name"] or 'Course Name' }}</h1>
            </div>
            <div class="col-md-4">
                <div class="card">
                    <img src="{{ url_for('static', filename='assests/images/tutor/daffa.png') }}" class="card-img-top" alt="tutor daffa">
                    <div class="card-body">
                    <form action="{{ url_for('course.payment', id=data['course_tutor_id']) }}" method="get">
                      <div class="row">
                        <div class="col">
                          <h5 class="card-title">{{ data["name"] or 'Course Tutor' }}</h5>
                        </div>
                        <div class="row">
                          <div class="col ms-3">
                            <p class="card-text">Tarif perjam</p>
                            <p class="card-text">Waktu (jam)</p> 
                            <p class="card-text mt-2">Jumlah murid</p> 
                          </div>
                          <div class="col isi">
                            <p class="text-end">Rp{{ data["hourly_fee"]|rupiah_format or '-' }}</p>
                            <input id="hours" type="number" name="hours" min="1" value="1" required>
                            <p class="text-end mt-3">50</p>
                          </div>
                          <!-- <input type="hidden" name="course_tutor_id" value="data['course_tutor_id']"> -->
                        </div>
                      </div>
                      {% if g.user %}
                      <div class="button-byr d-flex flex-column justify-content-center align-items-center ">
                        <!-- <a href="{{ url_for('course.payment', id=data['course_tutor_id']) }}" class="btn btn-bayar">Reservasi</a> -->
                        <button class="btn btn-bayar" type="submit">Reservasi</button>
                      </div>
                      <div class="button-cek d-flex flex-column justify-content-center align-items-center pt-2">
                        <a href="#" class="btn btn-bayar" placeholder="Masukan Keranjang">Masukan keranjang</a>
                      </div>
                      {% else %}
                      <div class="mb-2" style="color: red;">
                        <p style="text-align: center">Anda belum login!</p>
                      </div>
                      {% endif %}
                    </form>
                    </div>
                  </div>
            </div>
        </div>
    </div>
</section>

<!-- deskripsi kursus -->
<section class="description-course">
  <div class="container">
    <div class="row">
      <div class="col-md-8 deskripsi">
        <h5>Tentang course {{ data["course_name"] or 'Course Name' }} oleh {{ data["name"] or 'Course Tutor' }}</h5>
        <p>{{ data["course_description"] or 'Course Description' }}</p>
        <div class="desk-course">
          <i class='bx bx-book-alt'></i>
          <ul>
            <li>Programming</li>
            <li>HTML</li>
            <li>CSS</li>
            <li>Javascript</li>
          </ul>
        </div>
    </div>
    </div>
  </div>
</section>

<!-- deskripsi tutor -->
<section class="deskripsi-tutor d-flex flex-column justify-content-center align-items-center">
    <div class="container">
        <div class="row">
            <div class="col-md-8">
                <h5>Tentang {{ data["name"] or 'Course Tutor' }}</h5>
                <p>{{ data["self_description"] or "Lead Machine Learning Software Engineer at a startup company. Has 2 years experience in artificial intelligence and machine learning product development for various startup companies and projects. Graduated from the Department of Astronomy, Institut Teknologi Bandung. Previously won intel hackathon competition and national robotics competition. Has several lecture assistant experience and private tutorials." }}</p>
            </div>
        </div>
    </div>
</section>

<!-- Ulasan -->
<section class="ulasan d-flex flex-column justify-content-center align-items-center">
    <div class="container">
            <h5>Ulasan</h5>

        <div class="row">
            <div class="col-md-8 mb-3 mt-3">
                <h6>Naruto</h6>
                <img src="{{ url_for('static', filename='assests/images/categories/stars.png') }}" alt="stars">
                <p>keren banget. tutornya sabar.</p>
            </div>
        </div>
        <div class="row">
            <div class="col-md-8 mb-3">
                <h6>Himti</h6>
                <img src="{{ url_for('static', filename='assests/images/categories/stars.png') }}" alt="stars">
                <p>bang gift alok</p>
            </div>
        </div>
        <div class="row">
            <div class="col-md-8 mb-3">
                <h6>Naruto</h6>
                <img src="{{ url_for('static', filename='assests/images/categories/stars.png') }}" alt="stars">
                <p>proker cepet selesain cuy. asig harus diadain</p>
            </div>
        </div>
        <div class="row">
            <div class="col-md-8 mb-3">
                <h6>Nofan</h6>
                <img src="{{ url_for('static', filename='assests/images/categories/stars.png') }}" alt="stars">
                <p>otw dipanggil nasa</p>
            </div>
        </div>
    </div>
</section>
{% endblock %}

pator/templates/tutee/list.html
{% extends 'base.html' %}

{% block title %}Find Course{% endblock %}

{% block content %}

<section class="kategori-menu d-flex flex-column justify-content-center align-items-center">
    <div class="container">
        <h1>{{ category }}</h1>
        {% if datas|length == 0 %}
          <h4 class="mt-4">Maaf, tidak ada data!</h4>
        {% endif %}

        <!-- {% for data in datas %}
            <div>{{ data }}</div>
        {% endfor %} -->

        {% for data in datas %}
          {% if loop.index0 % 4 == 0 %}
            <div class="row">
          {% endif %}
              <div class="col-md-3 mb-3">
                <a href="{{ url_for('course.detail', id=data['course_tutor_id']) }}">
                  <div class="card">
                    <img src="{{ url_for('static', filename='assests/images/categories/TI.jpg') }}" class="card-img-top" alt="Course image">
                    <div class="card-body">
                      <p class="fs-6 fw-light">{{ data['course_prodi'].title() or "Course Category" }}</p>
                      <h5 class="card-text">{{ data['course_name'] or "Course Name" }}</h5>
                      <h6 class="students">{{ data["name"] or 'Course Tutor' }}</h6>
                      <img src="{{ url_for('static', filename='assests/images/categories/stars.png') }}" alt="stars" id="stars">
                      <p>IDR</p>
                      <p id="harga">{{ data['hourly_fee']|rupiah_format }}/jam</p>
                    </div>
                  </div>
                </a>
              </div>
          {% if loop.index0 % 4 == 3 %}
            </div>
          {% endif %}
        {% endfor %}
    </div>
</section>
{% endblock %}

pator/templates/tutee/payment.html
{% extends 'base.html' %}

{% block title %}Course Payment{% endblock %}

{% block content %}

 <!-- Pembayaran -->
 <section class="pembayaran d-flex flex-column justify-content-center align-items-center">
    <div class="container">
            <!-- <div>{{ data }}</div> -->
        <div class="row">
          <div class="col-md-4">
            <a href="{{ url_for('course.detail', id=data['course_tutor_id']) }}">
              <div class="card">
                <img src="{{ url_for('static', filename='assests/images/categories/TI.jpg') }}" class="card-img-top" alt="Teknik Informatika">
                <div class="card-body">
                    <p class="fs-5 fw-light">{{ data['course_prodi'] or "Course Category" }}</p>
                    <h5 class="card-text">{{ data['course_name'] or "Course Name" }}</h5>
                    <h6 class="students">{{ data["name"] or 'Course Tutor' }}</h6>
                    <img src="{{ url_for('static', filename='assests/images/categories/stars.png') }}" alt="stars" id="stars"S>
                    <p>IDR</p>
                    <p id="harga">{{ data['hourly_fee']|rupiah_format }}/jam</p>
                </div>
              </div>
            </a>
        </div>
                <div class="col-md-8 pembayaran2">
                    <h5>Total Pembayaran</h5>
                    <div class="row mt-5 mb-2">
                      <div class="col">
                        <p>Harga</p>
                      </div>
                      <div class="col">
                        <p class="text-end me-5">Rp {{ data['total_fee']|rupiah_format }}</p>
                      </div>
                    </div>
                    <p>Metode pembayaran</p>
                    <div class="tipe">
                        <button id="btn-ovo" class="btn"><span><img src="{{ url_for('static', filename='assests/images/pembayaran/ovo.png') }}" alt="ovo"></span></button>
                        <button id="btn-gopay" class="btn"><span><img src="{{ url_for('static', filename='assests/images/pembayaran/gopay.png') }}" alt="gopay" width="120px"></span></button>
                    </div>
                    <div class="btn-pesan">
                        <form action="{{ url_for('course.payment', id=data['course_tutor_id']) }}" method="post">
                          <input type="hidden" id="course_tutor_id" name="course_tutor_id" value="{{ data['course_tutor_id'] }}">
                          <input type="hidden" id="tutor_id" name="tutor_id" value="{{ data['id'] }}">
                          <button id="btn-pesan" class="btn" type="submit">Pesan</button>
                        </form>
                    </div>
                </div>
        </div>
    </div>
</section>


{% endblock %}

pator/templates/tutee/success.html
{% extends 'base.html' %}

{% block title %}Payment Success{% endblock %}

{% block content %}
<section class="sukses d-flex flex-column justify-content-center align-items-center">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-body">
                        <i class='bx bx-check-circle'></i>
                        <h1>Pembayaran sukses</h1>
                        <a href="{{ url_for('index') }}">Kembali ke home</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}