pator/blueprints/tutee.py
from flask import (
    Blueprint, flash, g, redirect, render_template, request, url_for
)
from jinja2 import TemplateNotFound
from werkzeug.exceptions import abort

from pator.blueprints.auth import login_required
from pator.db import get_db

bp = Blueprint('course', __name__, url_prefix='/course')
# bp_create = Blueprint('create', __name__, url_prefix='/create')

# bp.register_blueprint(bp_create)

def get_courses(query=None, type='category'):
    db = get_db()
    cursor = db.cursor(dictionary=True)

    #  if query is None, return every course
    if query is None:
        cursor.execute(
            '''
            SELECT c.course_name, c.course_prodi, cp.course_rating, cp.hourly_fee, cp.id AS course_tutor_id, u.name
            FROM course c
            INNER JOIN course_tutor cp ON (c.id = cp.course_id)
            INNER JOIN tutor t ON (cp.tutor_id = t.id)
            INNER JOIN user u ON (t.user_id = u.id)
            '''
        )
        
        datas = cursor.fetchall()

        return datas

    # if query is not none, execute query statement based on type
    if type == "category":
        category_name = f"%{query}%"

        cursor.execute(
            '''
            SELECT c.course_name, c.course_prodi, cp.course_rating, cp.hourly_fee, cp.id AS course_tutor_id, u.name
            FROM course c
            INNER JOIN course_tutor cp ON (c.id = cp.course_id)
            INNER JOIN tutor t ON (cp.tutor_id = t.id)
            INNER JOIN user u ON (t.user_id = u.id)
            WHERE c.course_prodi LIKE %s
            ''',
            (category_name,)
        )
    elif type == "search":
        search_query = f"%{query}%"

        cursor.execute(
            '''
            SELECT c.course_name, c.course_prodi, cp.course_rating, cp.hourly_fee, cp.id AS course_tutor_id, u.name
            FROM course c
            INNER JOIN course_tutor cp ON (c.id = cp.course_id)
            INNER JOIN tutor t ON (cp.tutor_id = t.id)
            INNER JOIN user u ON (t.user_id = u.id)
            WHERE c.course_name LIKE %s 
            OR u.name LIKE %s
            ''',
            (search_query, search_query,)
        )

    datas = cursor.fetchall()

    return datas


@bp.route('/category', defaults={'name': None})
@bp.route('/category/<name>', methods=(['GET']))
def category(name):
    datas = get_courses(name, "category")

    if name is not None:
        return render_template('tutee/list.html', datas=datas, category=name.title())
    else:
        return render_template('tutee/list.html', datas=datas)

@bp.route('/search', methods=(['GET']))
def search():
    query = request.args.get('query')
    
    datas = get_courses(query, "search")

    if query is not None:
        return render_template('tutee/list.html', datas=datas, category=query.title())
    else:
        return render_template('tutee/list.html', datas=datas)


@bp.route('/detail', defaults={'id': None})
@bp.route('/detail/<int:id>', methods=(['GET']))
def detail(id):
    db = get_db()
    cursor = db.cursor(dictionary=True)


    # TODO: Add more inner join to tables course_tutor_keyword and tutor_session_review
    cursor.execute(
        '''
        SELECT c.course_name, c.course_prodi, cp.course_rating, cp.hourly_fee, cp.id AS course_tutor_id, u.name,
        cp.course_description, t.self_description
        FROM course_tutor cp
        INNER JOIN course c ON (cp.course_id = c.id)
        INNER JOIN tutor t ON (cp.tutor_id = t.id)
        INNER JOIN user u ON (t.user_id = u.id)
        WHERE cp.id = %s
        ''',
        (id,)
    )

    data = cursor.fetchone()

    if data is not None:
        return render_template('tutee/detail.html', data=data)
    
    abort(404)

@bp.route('/payment', defaults={'id': None})
@bp.route('/payment/<int:id>', methods=('GET', 'POST'))
@login_required
def payment(id):
    if id is None:
        return redirect(request.referrer)

    if request.method == 'GET':
        hours = request.args.get('hours')

        db = get_db()
        cursor = db.cursor(dictionary=True)

        cursor.execute(
            '''
            SELECT c.course_name, c.course_prodi, cp.course_rating, cp.hourly_fee, cp.id AS course_tutor_id, u.name, u.id
            FROM course_tutor cp
            INNER JOIN course c ON (cp.course_id = c.id)
            INNER JOIN tutor t ON (cp.tutor_id = t.id)
            INNER JOIN user u ON (t.user_id = u.id)
            WHERE cp.id = %s
            ''',
            (id,)
        )

        data = cursor.fetchone()

        data['total_fee'] = data['hourly_fee'] * int(hours)

        if data is not None:
            return render_template('tutee/payment.html', data=data)
    
        abort(400)

    elif request.method == 'POST':
        course_tutor_id = request.form.get('course_tutor_id', None)
        tutor_id = request.form.get('tutor_id', None)
        user_id = g.user['id']

        db = get_db()
        cursor = db.cursor(dictionary=True)
        error = None

        if None in (course_tutor_id, tutor_id):
            error = "Please check you request data."

        if error is None:
            course_tutor_id = int(course_tutor_id)
            tutor_id = int(tutor_id)

            cursor.execute('SELECT * FROM tutee WHERE user_id = %s', (user_id,)) 

            tutee = cursor.fetchone()

            if tutee is None:
                cursor.execute('INSERT INTO tutee (user_id) VALUES (%s)', (user_id,))
                tutee_id = cursor.lastrowid
            else:
                tutee_id = tutee['id']

            cursor.execute(
                '''
                INSERT INTO tutor_session (course_tutor_id, tutor_id, tutee_id)
                VALUES (%s, %s, %s)
                ''',
                (course_tutor_id, tutor_id, tutee_id,)
            )

            return redirect(url_for('course.success'))

        abort(400)

@bp.route('/payment-success', methods=(['GET']))
def success():
    try:
        return render_template('tutee/success.html')
    except TemplateNotFound:
        abort(404)

pator/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock %} - Pator</title>

    <!-- CSS Bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='responsive.css') }}">

    <!-- Another CSS -->
    <link href="{{ url_for('static', filename='assests/vendors/boxicons/css/boxicons.min.css') }}" rel="stylesheet">
    <link href="{{ url_for('static', filename='assests/vendors/bootstrap-icons/bootstrap-icons.css') }}" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@500;600;700&display=swap" rel="stylesheet">
    <!-- Swiper CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swiper/swiper-bundle.min.css"/>
 
  </head>
  <body>
    {% include 'parts/nav.html' %}
    
    {% block content %}{% endblock %}

    {% if request.url_rule.endpoint != "auth.register" %}
      {% include 'parts/footer.html' %}
    {% else %}
      {% include 'parts/footer2.html' %}
    {% endif %}
    

    <!-- JS Bootstrap -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>

    <!-- Another JS -->
    <script src="https://cdn.jsdelivr.net/npm/swiper/swiper-bundle.min.js"></script>

    <script src="{{ url_for('static', filename='main.js') }}"></script>
  </body>
</html>

pator/templates/index.html
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
<!-- Hero Section -->
<section id="hero" class="d-flex flex-column justify-content-center align-items-center">
    <div class="container">
      <div class="row">
        <div class="col-md-6 hero-text">
          <h1>Ayo, Temukan <span style="color: #33A18E;">Mentor Tutor</span> Yang <span style="color: #33A18E">Terbaik</span> di Bidangnya </h1>
          <p>belajar kapanpun, dimanapun, tanpa batas</p>
          <form action="{{ url_for('course.search') }}" method="get">
            <input type="search" name="query" placeholder="Cari..." autocomplete="off">
            <label class="icon">
              <!-- <span><i class='bx bx-search'></i></span> -->
            </label>
            <button type="submit" class="btn join">Cari Tutor</button>
          </form>
        </div>
        <div class="col-md-6 hero-image">
          <img src="{{ url_for('static', filename='assests/images/hero/Group 1000006085.png') }}" alt="image1" width="650vh" height="auto">
        </div>
      </div>
    </div>
</section>

<!-- tutor section -->
<section class="tutor-section d-flex flex-column justify-content-center align-items-center">
    <div class="container">
      <div class="row">
        <div class="col-md-6 mt-5">
          <h1>Dengan mahasiswa terbaik</h1>
          <a href="{{ url_for('course.category') }}" class="btn btn-tutor">Temukan tutor anda</a>
        </div>
        <div class="col-md-6">
          <div class="swiper mySwiper">
            <div class="swiper-wrapper">
              <div class="swiper-slide">
                <div class="card">
                  <img src="{{ url_for('static', filename='assests/images/tutor/daffa.png') }}" class="card-img-top" alt="tutor daffa">
                  <div class="card-body">
                    <h5 class="card-title">Daffa Arviano</h5>
                    <p class="card-text">Mahasiswa Teknik Informatika terbaik, juara 1 hackathon.</p>
                  </div>
                </div>
              </div>
              <div class="swiper-slide">
                <div class="card">
                  <img src="{{ url_for('static', filename='assests/images/tutor/muaz.png') }}" class="card-img-top" alt="tutor daffa">
                  <div class="card-body">
                    <h5 class="card-title">Ahmad Muaz</h5>
                    <p class="card-text">Mahasiswa Teknik Informatika terbaik, menjuarai 1 UI/UX. </p>
                  </div>
                </div>
              </div>
              <div class="swiper-slide">
                <div class="card">
                  <img src="{{ url_for('static', filename='assests/images/tutor/daffa.png') }}" class="card-img-top" alt="tutor daffa">
                  <div class="card-body">
                    <h5 class="card-title">Daffa Arviano</h5>
                    <p class="card-text">Mahasiswa Teknik Informatika terbaik, juara 1 hackathon.</p>
                  </div>
                </div>
              </div>
              <div class="swiper-slide">
                <div class="card">
                  <img src="{{ url_for('static', filename='assests/images/tutor/muaz.png') }}" class="card-img-top" alt="tutor daffa">
                  <div class="card-body">
                    <h5 class="card-title">Ahmad Muaz</h5>
                    <p class="card-text">Mahasiswa Teknik Informatika terbaik, menjuarai 1 UI/UX. </p>
                  </div>
                </div>
              </div>
            </div>
            <div class="swiper-button-next"></div>
            <div class="swiper-button-prev"></div>
          </div>

        </div>
      </div>
    </div>
</section>


<!-- Top Categories -->
<section class="top-categories d-flex flex-column justify-content-center align-items-center">
    <div class="container">
      <section class="section-title">
        <h1>Tutorial terekomendasi</h1>
      </section>

      <div class="row">
        <div class="col-md-4 mb-3">
          <div class="card">
            <img src="{{ url_for('static', filename='assests/images/categories/TI.jpg') }}" class="card-img-top" alt="Teknik Informatika">
            <div class="card-body">
              <h5 class="card-text">Teknik Informatika</h5>
             <img src="{{ url_for('static', filename='assests/images/categories/stars.png') }}" alt="stars">
             <h6 class="students">50 Students</h6>
              <ul>
                <li>Studi Kasus</li>
                <li>Pengalaman</li>
                <li>Relasi Kerja</li>
              </ul>
            </div>
          </div>
        </div>
        <div class="col-md-4 mb-3">
          <div class="card">
            <img src="{{ url_for('static', filename='assests/images/categories/DKV.png') }}" class="card-img-top" alt="Desain Komunikasi Visual">
            <div class="card-body">
              <h5 class="card-text">Desain Komunikasi Visual</h5>
              <img src="{{ url_for('static', filename='assests/images/categories/stars.png') }}" alt="stars">
             <h6 class="students">50 Students</h6>
              <ul>
                <li>Studi Kasus</li>
                <li>Pengalaman</li>
                <li>Relasi Kerja</li>
              </ul>
            </div>
          </div>
        </div>
        <div class="col-md-4 mb-3">
          <div class="card">
            <img src="{{ url_for('static', filename='assests/images/categories/DP.jpg') }}" class="card-img-top" alt="Desain Produk">
            <div class="card-body">
              <h5 class="card-text">Desain Produk</h5>
              <img src="{{ url_for('static', filename='assests/images/categories/stars.png') }}" alt="stars">
             <h6 class="students">50 Students</h6>
              <ul>
                <li>Studi Kasus</li>
                <li>Pengalaman</li>
                <li>Relasi Kerja</li>
              </ul>
            </div>
          </div>
        </div>
      </div>
      <div class="row pt-5">
        <div class="col-md-4 mb-3">
          <div class="card">
            <img src="{{ url_for('static', filename='assests/images/categories/HI.jpg') }}" class="card-img-top" alt="Hubungan Internasional">
            <div class="card-body">
              <h5 class="card-text">Hubungan Internasional</h5>
              <img src="{{ url_for('static', filename='assests/images/categories/stars.png') }}" alt="stars">
             <h6 class="students">50 Students</h6>
              <ul>
                <li>Studi Kasus</li>
                <li>Pengalaman</li>
                <li>Relasi Kerja</li>
              </ul>
            </div>
          </div>
        </div>
        <div class="col-md-4 mb-3">
          <div class="card">
            <img src="{{ url_for('static', filename='assests/images/categories/psikologi.jpg') }}" class="card-img-top" alt="Psikologi">
            <div class="card-body">
              <h5 class="card-text">Psikologi</h5>
              <img src="{{ url_for('static', filename='assests/images/categories/stars.png') }}" alt="stars">
             <h6 class="students">50 Students</h6>
              <ul>
                <li>Studi Kasus</li>
                <li>Pengalaman</li>
                <li>Relasi Kerja</li>
              </ul>
            </div>
          </div>
        </div>
        <div class="col-md-4 mb-3">
          <div class="card">
            <img src="{{ url_for('static', filename='assests/images/categories/manajemen.jpg') }}" class="card-img-top" alt="Manajemen">
            <div class="card-body">
              <h5 class="card-text">Manajemen</h5>
              <img src="{{ url_for('static', filename='assests/images/categories/stars.png') }}" alt="stars">
             <h6 class="students">50 Students</h6>
              <ul>
                <li>Studi Kasus</li>
                <li>Pengalaman</li>
                <li>Relasi Kerja</li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
</section>

<!-- Join tutor -->
<section class="join-tutor d-flex flex-column justify-content-center align-items-center">
    <div class="container">
      <div class="row tutor-join d-flex justify-content-center align-items-center">
        <div class="col-md-6">
          <h1>Mari Bergabung Bersama Kami !!!</h1>
        </div>
        <div class="col-md-6 text-end">
          {% if g.user == None %}
            <a class="btn join" href="{{ url_for('auth.register') }}">Gabung</a>
          {% else %}
            <a class="btn join" href="{{ url_for('tutor.create.course') }}">Gabung</a>
          {% endif %}
        </div>
      </div>
    </div>
</section>
{% endblock %}