pator/blueprints/auth.py
import functools

from flask import (
    Blueprint, flash, g, redirect, render_template, request, session, url_for, abort
)
from jinja2 import TemplateNotFound

from werkzeug.security import check_password_hash, generate_password_hash

from pator.db import get_db

from mysql.connector import IntegrityError

bp = Blueprint('auth', __name__, url_prefix='/auth')

@bp.route('/register', methods=('GET', 'POST'))
def register():
    # print(dir(request))
    if request.method == 'POST':
        password = request.form.get('password', None)
        nim = request.form.get('nim', None)
        name = request.form.get('name', None)
        email = request.form.get('email', None)
        prodi = request.form.get('prodi', None)
        angkatan = request.form.get('angkatan', None)

        db = get_db()
        cursor = db.cursor(dictionary=True)
        error = None

        if None in (nim, password, name, email, prodi, angkatan):
            error = "Please fill all required data!"

        if error is None:
            try:
                data = (nim, generate_password_hash(password), name, email, prodi, angkatan)
                cursor.execute(
                    '''INSERT INTO user
                    (NIM, password, name, email, prodi, angkatan)
                    VALUES (%s, %s, %s, %s, %s, %s)''',
                    data,
                )
            except IntegrityError as e:
                err_msg = repr(e)
                if 'NIM' in err_msg:
                    error = f"Data NIM '{nim}' is already registered."
                elif 'email' in err_msg:
                    error = f"Data email '{email}' is already registered."
                else:
                    error = err_msg
            else:
                flash("Account has been created!", "success")
                return redirect(url_for("auth.register"))

        # print(error)

        flash(error, "error")

    try:
        return render_template('auth/register.html')
    except TemplateNotFound:
        abort(404)

# work in progress
@bp.route('/login', methods=('GET', 'POST'))
def login():
    if request.method == 'POST':
        account = request.form.get('account', None)
        password = request.form.get('password', None)

        db = get_db()
        cursor = db.cursor(dictionary=True)
        error = None

        if '@' in account:
            cursor.execute(
                "SELECT * FROM user WHERE email = %s", (account,)
            )
        else:
            cursor.execute(
                "SELECT * FROM user WHERE NIM = %s", (account,)
            )

        user = cursor.fetchone()

        print(user)

        if user is None:
            error = "Incorrect NIM or email."
        elif not check_password_hash(user['password'], password):
            error = "Incorrect password."

        # print(error)

        if error is None:
            session.clear()
            session['user_id'] = user['id']
            return redirect(url_for('index'))

        flash(error)

    try:
        return redirect(url_for('index'))
    except TemplateNotFound:
        abort(404)

@bp.before_app_request
def load_logged_in_user():
    user_id = session.get('user_id')

    if user_id is None:
        g.user = None
    else:
        cursor = get_db().cursor(dictionary=True)
        cursor.execute(
            "SELECT * FROM user WHERE id = %s", (user_id,)
        )
        g.user = cursor.fetchone()

@bp.route('/logout')
def logout():
    session.clear()
    return redirect(url_for('index'))

def get_user():
    return g.user

def login_required(view):
    @functools.wraps(view)
    def wrapped_view(**kwargs):
        if g.user is None:
            return redirect(url_for('auth.login'))

        return view(**kwargs)

    return wrapped_view

pator/blueprints/tutee.py
from flask import (
    Blueprint, flash, g, redirect, render_template, request, url_for
)
from jinja2 import TemplateNotFound
from werkzeug.exceptions import abort

from pator.blueprints.auth import login_required
from pator.db import get_db

bp = Blueprint('course', __name__, url_prefix='/course')
# bp_create = Blueprint('create', __name__, url_prefix='/create')

# bp.register_blueprint(bp_create)

def get_courses(query=None, type='category'):
    db = get_db()
    cursor = db.cursor(dictionary=True)

    #  if query is None, return every course
    if query is None:
        cursor.execute(
            '''
            SELECT c.course_name, c.course_prodi, cp.course_rating, cp.hourly_fee, cp.id AS course_tutor_id, u.name
            FROM course c
            INNER JOIN course_tutor cp ON (c.id = cp.course_id)
            INNER JOIN tutor t ON (cp.tutor_id = t.id)
            INNER JOIN user u ON (t.user_id = u.id)
            '''
        )
        
        datas = cursor.fetchall()

        return datas

    # if query is not none, execute query statement based on type
    if type == "category":
        category_name = f"%{query}%"

        cursor.execute(
            '''
            SELECT c.course_name, c.course_prodi, cp.course_rating, cp.hourly_fee, cp.id AS course_tutor_id, u.name
            FROM course c
            INNER JOIN course_tutor cp ON (c.id = cp.course_id)
            INNER JOIN tutor t ON (cp.tutor_id = t.id)
            INNER JOIN user u ON (t.user_id = u.id)
            WHERE c.course_prodi LIKE %s
            ''',
            (category_name,)
        )
    elif type == "search":
        search_query = f"%{query}%"

        cursor.execute(
            '''
            SELECT c.course_name, c.course_prodi, cp.course_rating, cp.hourly_fee, cp.id AS course_tutor_id, u.name
            FROM course c
            INNER JOIN course_tutor cp ON (c.id = cp.course_id)
            INNER JOIN tutor t ON (cp.tutor_id = t.id)
            INNER JOIN user u ON (t.user_id = u.id)
            WHERE c.course_name LIKE %s 
            OR u.name LIKE %s
            ''',
            (search_query, search_query,)
        )

    datas = cursor.fetchall()

    return datas


@bp.route('/category', defaults={'name': None})
@bp.route('/category/<name>', methods=(['GET']))
def category(name):
    datas = get_courses(name, "category")

    if name is not None:
        return render_template('tutee/list.html', datas=datas, category=name.title())
    else:
        return render_template('tutee/list.html', datas=datas)

@bp.route('/search', methods=(['GET']))
def search():
    query = request.args.get('query')
    
    datas = get_courses(query, "search")

    if query is not None:
        return render_template('tutee/list.html', datas=datas, category=query.title())
    else:
        return render_template('tutee/list.html', datas=datas)


@bp.route('/detail', defaults={'id': None})
@bp.route('/detail/<int:id>', methods=(['GET']))
def detail(id):
    db = get_db()
    cursor = db.cursor(dictionary=True)


    # TODO: Add more inner join to tables course_tutor_keyword and tutor_session_review
    cursor.execute(
        '''
        SELECT c.course_name, c.course_prodi, cp.course_rating, cp.hourly_fee, cp.id AS course_tutor_id, u.name,
        cp.course_description, t.self_description
        FROM course_tutor cp
        INNER JOIN course c ON (cp.course_id = c.id)
        INNER JOIN tutor t ON (cp.tutor_id = t.id)
        INNER JOIN user u ON (t.user_id = u.id)
        WHERE cp.id = %s
        ''',
        (id,)
    )

    data = cursor.fetchone()

    if data is not None:
        return render_template('tutee/detail.html', data=data)
    
    abort(404)

@bp.route('/payment', defaults={'id': None})
@bp.route('/payment/<int:id>', methods=('GET', 'POST'))
@login_required
def payment(id):
    if id is None:
        return redirect(request.referrer)

    if request.method == 'GET':
        hours = request.args.get('hours')

        db = get_db()
        cursor = db.cursor(dictionary=True)

        cursor.execute(
            '''
            SELECT c.course_name, c.course_prodi, cp.course_rating, cp.hourly_fee, cp.id AS course_tutor_id, u.name, u.id
            FROM course_tutor cp
            INNER JOIN course c ON (cp.course_id = c.id)
            INNER JOIN tutor t ON (cp.tutor_id = t.id)
            INNER JOIN user u ON (t.user_id = u.id)
            WHERE cp.id = %s
            ''',
            (id,)
        )

        data = cursor.fetchone()

        data['total_fee'] = data['hourly_fee'] * int(hours)

        if data is not None:
            return render_template('tutee/payment.html', data=data)
    
        abort(400)

    elif request.method == 'POST':
        course_tutor_id = request.form.get('course_tutor_id', None)
        tutor_id = request.form.get('tutor_id', None)
        user_id = g.user['id']

        db = get_db()
        cursor = db.cursor(dictionary=True)
        error = None

        if None in (course_tutor_id, tutor_id):
            error = "Please check you request data."

        if error is None:
            course_tutor_id = int(course_tutor_id)
            tutor_id = int(tutor_id)

            cursor.execute('SELECT * FROM tutee WHERE user_id = %s', (user_id,)) 

            tutee = cursor.fetchone()

            if tutee is None:
                cursor.execute('INSERT INTO tutee (user_id) VALUES (%s)', (user_id,))
                tutee_id = cursor.lastrowid
            else:
                tutee_id = tutee['id']

            cursor.execute(
                '''
                INSERT INTO tutor_session (course_tutor_id, tutor_id, tutee_id)
                VALUES (%s, %s, %s)
                ''',
                (course_tutor_id, tutor_id, tutee_id,)
            )

            return redirect(url_for('course.success'))

        abort(400)

@bp.route('/payment-success', methods=(['GET']))
def success():
    try:
        return render_template('tutee/success.html')
    except TemplateNotFound:
        abort(404)

pator/templates/parts/footer.html
<!-- Footer -->
<section class="footer">
    <div class="container">
      <div class="row">
        <div class="col-md-3">
        <img src="{{ url_for('static', filename='assests/images/pator.png.png') }}" alt="logo" width="200px">
        <p>Jl. Gatot Subroto No.Kav. 97, RT.4/RW.4, Mampang Prpt., Kec. Mampang Prpt., Kota Jakarta Selatan, Daerah Khusus Ibukota Jakarta 12790</p>
        </div>
        <div class="col-md-3">
          <h5>Feature</h5>
          <ul>
            <li><a href="#">Home</a></li>
            <li><a href="#">Tentang</a></li>
            <li><a href="#">Testimonial</a></li>
          </ul>
          
        </div>
        <div class="col-md-3">
          <h5>Tentang kami</h5>
          <ul>
            <li><a href="#">Tentang</a></li>
            <li><a href="#">Syarat dan ketentuan</a></li>
            <li><a href="#">Kebijakan privasi</a></li>
          </ul>
        </div>
        <div class="col-md-3 contact">
          <h5>Kontak kami</h5>
            <a href="#" class="whatsapp"><i class="bx bxl-whatsapp"></i></a>
            <a href="#" class="instagram"><i class="bx bxl-instagram"></i></a>
            <a href="#" class="email"><i class="bi bi-envelope"></i></a>
        </div>
      </div>
    </div>
</section>

pator/templates/parts/footer2.html
<!-- Footer -->
<section class="footer2">
    <div class="container">
        <div class="row">
            <div class="col-md-3">
            <img src="/hackathon/assests/images/pator.png.png" alt="logo" width="200px">
            <p>Jl. Gatot Subroto No.Kav. 97, RT.4/RW.4, Mampang Prpt., Kec. Mampang Prpt., Kota Jakarta Selatan, Daerah Khusus Ibukota Jakarta 12790</p>
            </div>
            <div class="col-md-3">
            <h5>Feature</h5>
            <ul>
                <li><a href="#">Home</a></li>
                <li><a href="#">Tentang</a></li>
                <li><a href="#">Testimonial</a></li>
            </ul>
            </div>
            <div class="col-md-3 about">
            <h5>Tentang kami</h5>
            <ul>
                <li><a href="#">Tentang</a></li>
                <li><a href="#">Syarat dan ketentuan</a></li>
                <li><a href="#">Kebijakan privasi</a></li>
            </ul>
            </div>
            <div class="col-md-3 contact">
            <h5>Kontak kami</h5>
                <a href="#" class="whatsapp"><i class="bx bxl-whatsapp"></i></a>
                <a href="#" class="instagram"><i class="bx bxl-instagram"></i></a>
                <a href="#" class="email"><i class="bi bi-envelope"></i></a>
            </div>
        </div>
    </div>
</section>

pator/templates/parts/nav.html
<nav class="navbar navbar-expand-lg fixed-top">
    <div class="container">
      <a class="navbar-brand" href="{{ url_for('index') }}">
        <img src="{{ url_for('static', filename='assests/images/pator.png.png') }}" alt="logo" width="150px">
      </a> 
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-auto">
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('index') }}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" aria-current="page" href="#">Kategori</a>
            <div class="dropdown-menu">
              <ul id="submenu-drop">
                <a href="{{ url_for('course.category', name='hubungan internasional') }}"><li>Hubungan Internasional</li></a>
                <a href="{{ url_for('course.category', name='psikologi') }}"><li>Psikologi</li></a>
                <a href="{{ url_for('course.category', name='desain komunikasi visual') }}"><li>Desain Komunikasi Visual</li></a>
                <a href="{{ url_for('course.category', name='desain produk') }}"><li>Desain Produk</li></a>
                <a href="{{ url_for('course.category', name='ilmu komunikasi') }}"><li>Ilmu Komunikasi</li></a>
                <a href="{{ url_for('course.category', name='teknik informatika') }}"><li>Teknik Informatika</li></a>
                <a href="{{ url_for('course.category', name='manajemen') }}"><li>Manajemen</li></a>
                <a href="{{ url_for('course.category', name='umum') }}"><li>Matakuliah Umum</li></a>
              </ul>
            </div>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Tentang</a>
          </li>
        </ul>
        {% if g.user %}
          <div class="dropdown">
            <a class="btn btn-secondary dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false"><i class="bi bi-list"></i></a>
          
            <ul class="dropdown-menu">
              <li><a class="dropdown-item" href="#">Dashboard</a></li>
              <li><a class="dropdown-item" href="#">Pesan</a></li>
              <li><a class="dropdown-item" href="{{ url_for('tutor.create.course') }}">Buat iklan</a></li>
              <li><a class="dropdown-item " href="{{ url_for('profile.index') }}">Profil</a></li>
              <li><a class="dropdown-item" href="{{ url_for('auth.logout') }}">Keluar</a></li>
            </ul>
          </div>
        {% else %}
          {% if request.url_rule.endpoint != "auth.register" %}
            <div class="daftar">
                <a href="{{ url_for('auth.register') }}" class="btn btn-daftar">Daftar</a>
            </div>
            <div class="masuk">
              <button id="show-login" class="btn-masuk" onclick="showPopup()">Masuk</button>
            </div>
            <div class="popup">
              <div class="close-btn" onclick="closePopup()">&times;</div>
              <form action="{{ url_for('auth.login') }}" method="post" id="login-form" autocomplete="off">
              <div class="form">
                <h2>Masuk</h2>
                {% for message in get_flashed_messages() %}
                  <div style="color: red;">{{ message }}</div>
                {% endfor %}
                <div class="form-element">
                  <label for="email">Email or NIM</label>
                  <input type="text" id="email" name="account" placeholder="Masukan email">
                </div>
                <div class="form-element">
                  <label for="password">Password</label>
                  <input type="password" id="password" name="password" placeholder="Masukan email">
                </div>
                <div class="form-element">
                  <input type="checkbox" id="remember-me" placeholder="Masukan email">
                  <label for="remember-me">Remember me</label>
                </div>
                <div class="form-element">
                  <button type="submit" value="Masuk" class="btn">Masuk</button>
                </div>
                <div class="form-element">
                  <button class="btn btn-google"> <span><img src="{{ url_for('static', filename='assests/images/google.png') }}" alt="google" width="35px"></span> Masuk dengan google</button>
                </div>
                <div class="form-element">
                  <a href="#">Forgot password</a>
                </div>
              </div>
              </form>
            </div>
          {% endif %}
        {% endif %}

      </div>
    </div>
</nav>

<!-- <script type="text/javascript">
  $(document).on('submit','#login-form',function(e)
                  {
    console.log('hello');
    e.preventDefault();
    $.ajax({
      type:'POST',
      url:"{{ url_for('auth.login') }}" ,
      data:{
        usernmae: $("#username").val(),
        password: $("password").val()
      },
      success:function()
      {
        alert('saved');
      }
    })
  });
</script> -->